---
version: '3.7'

services:
  wordpress-db:
    image: mariadb:10.7
    container_name: wordpress-db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1  # Behebt die bekannten Startprobleme

  wordpress-app:
    image: wordpress:fpm-alpine
    container_name: wordpress-app
    restart: unless-stopped
    depends_on:
      - wordpress-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - default

  wordpress-web:
    image: nginx:alpine
    container_name: wordpress-web
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./logs:/var/log/nginx/
    links:
      - wordpress-app
    depends_on:
      - wordpress-app
    networks:
      - default
      - proxy

  wordpress-cache:
    image: redis:latest
    container_name: wordpress-cache
    restart: unless-stopped
    depends_on:
      - wordpress-app
    networks:
      - default

networks:
  proxy:
    external:
      name: proxy
  default:
    driver: bridge
